//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppStore.Youths.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class App
    {
        public int Id { get; set; }
        public string AppName { get; set; }
        public string AppPrice { get; set; }
        public string AppImg { get; set; }
        public int AppTypeId { get; set; }
        public int AppClassId { get; set; }
        public Nullable<bool> AppIsFree { get; set; }
        public Nullable<bool> AppIsNew { get; set; }
        public Nullable<bool> AppIsRecommended { get; set; }
        public string AppDeveloper { get; set; }
        public string AppVersion { get; set; }
        public Nullable<int> AppDownload { get; set; }
        public string AppSize { get; set; }
        public string AppIntroduce { get; set; }
        public string AppDescribe { get; set; }

        [DefaultValue("http://app.res.meizu.com/cabs/freeapk/1371/ctrip.android.view_6.1.1_1420426248.apk")]
        public string AppUrl { get; set; }
        public System.DateTime AddTime { get; set; }
        public System.DateTime UpdateTime { get; set; }

        public virtual AppClass AppClass { get; set; }
        public virtual ICollection<AppComment> AppComments { get; set; }
        public virtual ICollection<AppScreenShot> AppScreenShots { get; set; }

        
    }
}
